[tool.poetry]
name = "circuitree"
version = "0.1.0"
description = "Genetic circuit design using Monte Carlo tree search"
authors = ["pranav-bhamidipati <pbhamidi@usc.edu>"]
license = "GPLv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.10"
numpy = "^1.23.0"
scipy = "^1.10.1"
pandas = "^2.0.0"
matplotlib = "^3.7.1"
tqdm = "^4.65.0"
networkx = "^3.1"
numba = "^0.56.4"
datashader = "^0.14.4"
psutil = "^5.9.4"
hiveplotlib = "^0.21"
h5py = "^3.8.0"
more-itertools = "^9.1.0"
sacred = "^0.8.4"
seaborn = "^0.12.2"
pyarrow = "^12.0.0"

[tool.poetry.group.dev.dependencies]
ipython = "^8.12.0"
black = "^23.3.0"
line-profiler = {extras = ["python"], version = "^4.0.3"}
fastapi = "^0.95.0"
ipykernel = "^6.23.1"
tuna = "^0.5.11"
jupyterlab = "^4.0.0"
ipywidgets = "^8.0.6"
dask = {extras = ["distributed"], version = "^2023.5.0"}
nodejs = "^0.1.1"
ipympl = "^0.9.3"
dask-labextension = "^6.1.0"
ray = {extras = ["default"], version = "^2.4.0"}
tables = "^3.8.0"
biocircuits = "^0.1.11"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
in-project = true
prefer-active-python = true

